version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8081:80
    networks:
      - web
  db:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/dblaundry.sql:/docker-entrypoint-initdb.d/dblaundry.sql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dblaundry
    ports:
      - "3333:3306"
    networks:
      - web
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db
    networks:
      - web
networks:
  web:
    driver: bridge
volumes:
  dbdata:
